remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Nathaniel A. Throckmorton, Ph.D.
description: 
    Tang Associate Professor
    
    Economics Department
    
    William & Mary
    
    [nat@wm.edu](mailto:nat@wm.edu)